
// This file is auto-generated by the build system.
// Please do not edit this file directly.

// We can't use 'satisfies' in the package.json file, so we'll use this file
// to hint to the user that they should use it.

// For example:
// import type { Config } from 'tailwindcss'

// export default {
//   ...
// } satisfies Config

// Path: tailwind.config.ts
// import type { Config } from 'tailwindcss'

// export default {
//   ...
// } satisfies Config

// Path: postcss.config.mjs
// import type { Config } from 'postcss-load-config'

// export default {
//   ...
// } satisfies Config

// Path: prettier.config.mjs
// import type { Config } from 'prettier'

// export default {
//   ...
// } satisfies Config

// Path: next.config.mjs
// import type { NextConfig } from 'next'

// export default {
//   ...
// } satisfies NextConfig
